server:
  port: 8080
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
logging:
  file:
    path: /var/tmp/mylog.log
jwt:
  token:
    validity: 18000000
    secret: FdWeb3d
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/web3d?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
#    docker
#    url: jdbc:mysql://mysql:3306/web3d?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    tomcat:
      max-wait: 10000
    dbcp2:
      max-idle: 10
      min-idle: 1
      initial-size: 5
      max-conn-lifetime-millis: 27000000
    hikari:
      connection-timeout: 600000
      maximum-pool-size: 500
      max-lifetime: 1800000
      minimum-idle: 20
      validation-timeout: 3000
      idle-timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
socketio:
  host: 127.0.0.1
  port: 9091
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  upgradeTimeout: 1000000
  pingTimeout: 6000000
  pingInterval: 25000





